version: '3.4'

services:
  db:
    image: mariadb
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-whocares}

  cli:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes: 
      - wp_volume:/var/www/html

  wordpress:
    image: wordpress
    depends_on:
      - cli
    volumes:
      - wp_volume:/var/www/html
    ports:
      - ${WP_PORT:-1234}:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-whocares}
      WORDPRESS_DB_HOST: db:3306
  
volumes:
  db_volume:
  wp_volume: